<script lang='ts'>
  import { invoke } from "@tauri-apps/api/core";
  import { open } from "@tauri-apps/plugin-dialog";
  import { goto } from '$app/navigation'
  import { error } from "@sveltejs/kit";

  let file_path: string | null = $state(null)
  let err: string | null = $state(null)

  async function open_xml() {
    err = null
    const file = await open({
      multiple: false,
      directory: false,
    })

    if (file) {
      file_path = file
      invoke<null>('parse_xml', {path: file_path})
        .then( _ => goto('./select'))
        .catch(e => {
          file_path = null
          err = String(e)
        })
    }
  }
</script>

<main class="container">
  <h1>Harmony Image Downloader</h1>

  {#if err !== null}
    <div class="error">
      <h2> Error! </h2>
      {err}
    </div>
  {/if}

  {#if file_path === null}
    <button onclick={open_xml}>Select Export XML</button>
    <p>The proper XML file is generated by Harmony when you export data.</p>
    <p>Choose the "Measurement with Assoc. Images" option, 
      and select the <code>Index.xml</code> file.
    </p>
  {:else}
    <h2>Parsing XML</h2>
    <div class="centered">
      <span class="loader"></span>
    </div>
    <p> {file_path} </p>
  {/if}
</main>

<style>
  .container {
    margin: 0rem 1.5rem;
    padding-top: 6vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    text-align: center;
  }
  .error {
    background-color: darkred;
    padding: 1rem 2rem;
    margin: 1rem 0;
    font-weight: 800;
    border-radius: 1rem;
    white-space: pre-wrap;
    text-align: left;
  }
  .error h2 {
    text-align: center;
  }
  .centered {
    display: flex;
    justify-content: center;
    text-align: center;
  }
  .loader {
    width: 72px;
    height: 72px;
    border-radius: 50%;
    position: inherit;
    animation: rotate 1s linear infinite
  }
  .loader::before , .loader::after {
    content: "";
    box-sizing: border-box;
    position: absolute;
    inset: 0px;
    border-radius: 50%;
    border: 5px solid #FFF;
    animation: prixClipFix 2s linear infinite ;
  }
  .loader::after{
    transform: rotate3d(90, 90, 0, 180deg );
    border-color: #FF3D00;
  }

  @keyframes rotate {
    0%   {transform: rotate(0deg)}
    100%   {transform: rotate(360deg)}
  }

  @keyframes prixClipFix {
      0%   {clip-path:polygon(50% 50%,0 0,0 0,0 0,0 0,0 0)}
      50%  {clip-path:polygon(50% 50%,0 0,100% 0,100% 0,100% 0,100% 0)}
      75%, 100%  {clip-path:polygon(50% 50%,0 0,100% 0,100% 100%,100% 100%,100% 100%)}
  }
</style>
